### PR TITLE
Moved all events to single namespace.

### PR DESCRIPTION
**Pull request by RigidStudios**
Allows for more event listeners theoretically, less different namespaces to navigate through, clearer when looking at the DBM Object. It is intentionally called `events` and not `Events`. This was tested for SyntaxErrors, but not for functionality on most events. In some places with 
```const { Bot, Actions } = DBM;```
I made that be in the root scope of `mod:` to not have to call DBM.Bot for `.onReady` and `.bot.on(...)`.
Minor Capitalization changes, a few comment removals, added "Temp Variable Name" to my events to make it more clear.

### CODE REVIEW

**Comment by RigidStudios** [comment]
Now uses `.forEach()` (Slightly Faster), ESLint issues fixed.

**Review by almeidx — CHANGES_REQUESTED** [review]
don't use forEach

**Comment by RigidStudios** [comment]
eslint issues fixed*

**Review by almeidx — CHANGES_REQUESTED** [review]
Rename `DBM.events` to `DBM.Events`

**Review by almeidx — APPROVED** [review]

**Pull request merged**
